ARG TERRAFORM_VERSION=v1.9
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v2.0.3-alpine

ARG TARGETPLATFORM

USER root

## Azure cli
RUN apk add --no-cache --force-broken-world \
        python3 \
        py3-pip \
        gcc \
        musl-dev \
        python3-dev \
        libffi-dev \
        openssl-dev \
        cargo \
        make && \
    rm -rf /var/cache/apk/* && \
    pip3 install --upgrade --break-system-packages pip && \
    pip3 install --break-system-packages azure-cli

USER devops

RUN az --version

