ARG TERRAFORM_VERSION=v1.2
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v1.4.7-fedora

ARG TARGETPLATFORM

## Azure cli
RUN sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    sudo dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm && \
    sudo dnf install -y azure-cli && \
    sudo dnf clean all && \
    az --version
