ARG TERRAFORM_VERSION=v1.2
FROM quay.io/cloudnativetoolkit/cli-tools-core:${TERRAFORM_VERSION}-v1.2.1-fedora

ARG TARGETPLATFORM

## Azure cli
RUN sudo dnf install -y gcc musl-devel python3-devel libffi-devel openssl-devel cargo make python3 python3-pip \
    && sudo pip3 install --upgrade pip \
    && sudo pip3 install azure-cli \
    && sudo dnf clean all \
    && az --version
